#ifndef MODULE_CHARTYPEREGEX_H
#define MODULE_CHARTYPEREGEX_H

enum {
	INVALID_CHARTYPE = 'X',
	DATA_CHARTYPE = '#',
	OR_CHARTYPE = '|',
	AND_CHARTYPE = '&',
	BEGIN_GROUP_CHARTYPE = '(',
	END_GROUP_CHARTYPE = ')',
	BEGIN_TEXT_CHARTYPE = '^',
	END_TEXT_CHARTYPE = '$',
	KLEENE_STAR_CHARTYPE = '*',
	OPTIONAL_MARK_CHARTYPE = '?'
};

#endif
