#ifndef MODULE_TESTING_H
#define MODULE_TESTING_H

//Whole Program
//#define TESTING_PROGRAM

//Regex Package
//#define TESTING_REGEX
#define TESTING_GRAPHREGEX

//Condition Package
#define TESTING_CONDITION_PACKAGE
//#define TESTING_CONDITION_BUILDER
//#define TESTING_CONDITION_CONDLIST
//#define TESTING_CONDITION_MAKER
//#define TESTING_CONDITION_NODE
//#define TESTING_CONDITION_PARSESTRING

#endif
